//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentService_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentService_cu()
        {
            this.AppointmentTransactions = new HashSet<AppointmentTransaction>();
        }
    
        public int ID { get; set; }
        public int Service_CU_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ColorR { get; set; }
        public Nullable<int> ColorG { get; set; }
        public Nullable<int> ColorB { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual User_cu User_cu { get; set; }
        public virtual Service_cu Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransaction> AppointmentTransactions { get; set; }
    }
}
