//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentTransaction()
        {
            this.AppointmentTransactionSendingDetails = new HashSet<AppointmentTransactionSendingDetail>();
        }
    
        public int ID { get; set; }
        public int AppointmentDoctor_CU_ID { get; set; }
        public int AppointmentService_CU_ID { get; set; }
        public long Patient_CU_ID { get; set; }
        public int AppointmentType_CU_ID { get; set; }
        public int AppointmentStatus_P_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<System.DateTime> QueryStartDate { get; set; }
        public Nullable<System.DateTime> QueryEndDate { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public Nullable<int> Type { get; set; }
        public string Location { get; set; }
        public string ReminderInfo { get; set; }
        public string RecurrenceInfo { get; set; }
        public string TimeZoneId { get; set; }
        public bool IsOnDuty { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<int> InsertedYear { get; set; }
        public Nullable<int> InsertedMonth { get; set; }
        public Nullable<int> InsertedDay { get; set; }
    
        public virtual AppointmentDoctor_cu AppointmentDoctor_cu { get; set; }
        public virtual AppointmentService_cu AppointmentService_cu { get; set; }
        public virtual AppointmentStatus_p AppointmentStatus_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual AppointmentType_cu AppointmentType_cu { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails { get; set; }
    }
}
