//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTransactionSendingDetail
    {
        public int ID { get; set; }
        public int AppointmentTransactionID { get; set; }
        public Nullable<bool> SendMobile1WhatsApp { get; set; }
        public string Mobile1MessageSent { get; set; }
        public Nullable<long> Mobile1User_CU_ID { get; set; }
        public Nullable<bool> SendMobile2WhatsApp { get; set; }
        public string Mobile2MessageSent { get; set; }
        public Nullable<long> Mobile2User_CU_ID { get; set; }
        public Nullable<bool> CallPhone1 { get; set; }
        public Nullable<long> CallPhone1User_CU_ID { get; set; }
        public Nullable<bool> CallPhone2 { get; set; }
        public Nullable<long> CallPhone2User_CU_ID { get; set; }
        public Nullable<bool> SendPatientEmail { get; set; }
        public Nullable<long> PatientSendEmail_User_CU_ID { get; set; }
        public Nullable<bool> SendDoctorWhatsApp { get; set; }
        public Nullable<long> SendDoctorWhatsApp_CU_ID { get; set; }
        public Nullable<bool> SendDoctorEmail { get; set; }
        public Nullable<long> DoctorSendEmail_User_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual AppointmentTransaction AppointmentTransaction { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual User_cu User_cu1 { get; set; }
        public virtual User_cu User_cu2 { get; set; }
        public virtual User_cu User_cu3 { get; set; }
        public virtual User_cu User_cu4 { get; set; }
        public virtual User_cu User_cu5 { get; set; }
        public virtual User_cu User_cu6 { get; set; }
        public virtual User_cu User_cu7 { get; set; }
    }
}
