//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxPrintingConfiguration_cu
    {
        public int ID { get; set; }
        public int CashBoxTransactionSignatureType_P_ID { get; set; }
        public bool OnBottom { get; set; }
        public Nullable<int> OrderIndexFromRightInArabic { get; set; }
        public Nullable<int> OrderIndexFromLeftInEnglish { get; set; }
        public bool AppearInPrinting { get; set; }
        public bool AppearInApplicationReports { get; set; }
        public string Description { get; set; }
        public bool ShowDescriptionInPrinting { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual CashBoxTransactionSignatureType_p CashBoxTransactionSignatureType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
