//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChartOfAccount_cu()
        {
            this.Bank_cu = new HashSet<Bank_cu>();
            this.BankAccount_cu = new HashSet<BankAccount_cu>();
            this.CashBox_cu = new HashSet<CashBox_cu>();
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.ChartOfAccount_cu1 = new HashSet<ChartOfAccount_cu>();
            this.ChartOfAccountBalances = new HashSet<ChartOfAccountBalance>();
            this.InsuranceCarrier_cu = new HashSet<InsuranceCarrier_cu>();
            this.InventoryStore_cu = new HashSet<InventoryStore_cu>();
            this.InventoryItemBrand_cu = new HashSet<InventoryItemBrand_cu>();
            this.InventoryItemCategory_cu = new HashSet<InventoryItemCategory_cu>();
            this.InventoryItemGroup_cu = new HashSet<InventoryItemGroup_cu>();
            this.Person_ChartOfAccount_cu = new HashSet<Person_ChartOfAccount_cu>();
            this.Service_cu = new HashSet<Service_cu>();
            this.ServiceCategory_cu = new HashSet<ServiceCategory_cu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentChartOfAccount_CU_ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public long Serial { get; set; }
        public int ChartOfAccountCodeMargin_P_ID { get; set; }
        public bool IsDebit { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank_cu> Bank_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount_cu> BankAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBox_cu> CashBox_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_cu> ChartOfAccount_cu1 { get; set; }
        public virtual ChartOfAccount_cu ChartOfAccount_cu2 { get; set; }
        public virtual ChartOfAccountCodeMargin_p ChartOfAccountCodeMargin_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccountBalance> ChartOfAccountBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_cu> InsuranceCarrier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStore_cu> InventoryStore_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemBrand_cu> InventoryItemBrand_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemCategory_cu> InventoryItemCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroup_cu> InventoryItemGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_ChartOfAccount_cu> Person_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_cu> ServiceCategory_cu { get; set; }
    }
}
