//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_cu()
        {
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
        }
    
        public long Person_CU_ID { get; set; }
        public Nullable<int> CustomerType_P_ID { get; set; }
        public string InternalCode { get; set; }
        public string Description { get; set; }
    
        public virtual CustomerType_p CustomerType_p { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
    }
}
