//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor_cu()
        {
            this.AppointmentDoctor_cu = new HashSet<AppointmentDoctor_cu>();
        }
    
        public long Person_CU_ID { get; set; }
        public Nullable<int> DoctorTitle_P_ID { get; set; }
        public Nullable<int> DoctorCategory_CU_ID { get; set; }
        public Nullable<int> DoctorTaxType_CU_ID { get; set; }
        public Nullable<int> DoctorRank_P_ID { get; set; }
        public Nullable<int> DoctorProfessionalFeesIssuingType_P_ID { get; set; }
        public string PrivateMobile { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public string InternalCode { get; set; }
        public Nullable<double> DoctorShare { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentDoctor_cu> AppointmentDoctor_cu { get; set; }
        public virtual DoctorCategory_cu DoctorCategory_cu { get; set; }
        public virtual DoctorProfessionalFeesIssuingType_p DoctorProfessionalFeesIssuingType_p { get; set; }
        public virtual DoctorRank_p DoctorRank_p { get; set; }
        public virtual DoctorTaxType_cu DoctorTaxType_cu { get; set; }
        public virtual Person_cu Person_cu { get; set; }
    }
}
