//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCarrier_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCarrier_cu()
        {
            this.InsuranceCarrier_InsuranceLevel_cu = new HashSet<InsuranceCarrier_InsuranceLevel_cu>();
            this.InsuranceLevel_cu = new HashSet<InsuranceLevel_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public string InternalCode { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> ChartOfAccount_CU_ID { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_InsuranceLevel_cu> InsuranceCarrier_InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceLevel_cu> InsuranceLevel_cu { get; set; }
    }
}
