//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem_cu()
        {
            this.InventoryItem_PurchasingTax_cu = new HashSet<InventoryItem_PurchasingTax_cu>();
            this.InventoryItem_SellingTax_cu = new HashSet<InventoryItem_SellingTax_cu>();
            this.InventoryItem_UnitMeasurment_cu = new HashSet<InventoryItem_UnitMeasurment_cu>();
            this.InventoryItemGroup_InventoryItem_cu = new HashSet<InventoryItemGroup_InventoryItem_cu>();
            this.InventoryItemGroupingItem_cu = new HashSet<InventoryItemGroupingItem_cu>();
            this.InventoryItemOffers_cu = new HashSet<InventoryItemOffers_cu>();
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
            this.InventoryItemSize_cu = new HashSet<InventoryItemSize_cu>();
            this.InventoryTrackingPeriod_cu = new HashSet<InventoryTrackingPeriod_cu>();
            this.InventoryTransferTransactions = new HashSet<InventoryTransferTransaction>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsCountable { get; set; }
        public string InternalCode { get; set; }
        public string ItemSKU { get; set; }
        public string AbbreviationName { get; set; }
        public string DefaultBarcode { get; set; }
        public Nullable<int> InventoryItemCategory_CU_ID { get; set; }
        public Nullable<int> InventoryItemBrand_CU_ID { get; set; }
        public int InventoryItemStateSellingType_P_ID { get; set; }
        public int InventoryItemStatePurchasingType_P_ID { get; set; }
        public Nullable<int> InventoryItemType_P_ID { get; set; }
        public int InventoryItemInvoicingStrategy_P_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CustomerDaysLimit { get; set; }
        public Nullable<System.DateTime> SellingStartDate { get; set; }
        public Nullable<System.DateTime> SellingEndDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> SizeUnitMeasure_P_ID { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> AreaUnitMeasure_P_ID { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> VolumeUnitMeasure_P_ID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> WeightUnit_P_ID { get; set; }
        public Nullable<bool> UseElectronicScale { get; set; }
        public string InDescription { get; set; }
        public string OutDescription { get; set; }
        public Nullable<double> DefaultSellingPrice { get; set; }
        public Nullable<double> MinSellingPrice { get; set; }
        public Nullable<double> PurchasingPrice { get; set; }
        public string PurchasingDescription { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual InventoryItemBrand_cu InventoryItemBrand_cu { get; set; }
        public virtual InventoryItemCategory_cu InventoryItemCategory_cu { get; set; }
        public virtual InventoryItemType_p InventoryItemType_p { get; set; }
        public virtual SizeUnitMeasure_p SizeUnitMeasure_p { get; set; }
        public virtual SizeUnitMeasure_p SizeUnitMeasure_p1 { get; set; }
        public virtual SizeUnitMeasure_p SizeUnitMeasure_p2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual WeightUnit_p WeightUnit_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_PurchasingTax_cu> InventoryItem_PurchasingTax_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_SellingTax_cu> InventoryItem_SellingTax_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_UnitMeasurment_cu> InventoryItem_UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroup_InventoryItem_cu> InventoryItemGroup_InventoryItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroupingItem_cu> InventoryItemGroupingItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemOffers_cu> InventoryItemOffers_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemSize_cu> InventoryItemSize_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTrackingPeriod_cu> InventoryTrackingPeriod_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransferTransaction> InventoryTransferTransactions { get; set; }
    }
}
