//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStoreTreeLinks_cu
    {
        public long ID { get; set; }
        public long ParentInventoryStore_CU_ID { get; set; }
        public long ChildInventoryStore_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual InventoryStore_cu InventoryStore_cu { get; set; }
        public virtual InventoryStore_cu InventoryStore_cu1 { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
