//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemGroupingItem_cu
    {
        public int ID { get; set; }
        public int InventoryItemGrouping_CU_ID { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public Nullable<int> InventoryItemSize_CU_ID { get; set; }
        public bool IsMain { get; set; }
        public int Count { get; set; }
        public bool IsOnDuty { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual InventoryItemGrouping_cu InventoryItemGrouping_cu { get; set; }
        public virtual InventoryItemSize_cu InventoryItemSize_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
