//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStore_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryStore_cu()
        {
            this.InventoryRequestTransfers = new HashSet<InventoryRequestTransfer>();
            this.InventoryStore_cu1 = new HashSet<InventoryStore_cu>();
            this.InventoryStoreTreeLinks_cu = new HashSet<InventoryStoreTreeLinks_cu>();
            this.InventoryStoreTreeLinks_cu1 = new HashSet<InventoryStoreTreeLinks_cu>();
            this.InventoryTrackingPeriod_cu = new HashSet<InventoryTrackingPeriod_cu>();
            this.InventoryTransferTransactions = new HashSet<InventoryTransferTransaction>();
            this.InventoryTransferTransactions1 = new HashSet<InventoryTransferTransaction>();
        }
    
        public long ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<long> ParentInventoryStore_CU_ID { get; set; }
        public Nullable<long> InventoryCategory_CU_ID { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public bool IsMain { get; set; }
        public Nullable<bool> UseAcceptReceive { get; set; }
        public Nullable<long> Department_CU_ID { get; set; }
        public Nullable<long> InChargeID { get; set; }
        public Nullable<long> Location_CU_ID { get; set; }
        public Nullable<long> Floor_CU_ID { get; set; }
        public Nullable<int> ChartOfAccount_CU_ID { get; set; }
        public string InternalCode { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
        public virtual Department_cu Department_cu { get; set; }
        public virtual Employee_cu Employee_cu { get; set; }
        public virtual Floor_cu Floor_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryRequestTransfer> InventoryRequestTransfers { get; set; }
        public virtual Location_cu Location_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStore_cu> InventoryStore_cu1 { get; set; }
        public virtual InventoryStore_cu InventoryStore_cu2 { get; set; }
        public virtual InventoryStoreCategory_cu InventoryStoreCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStoreTreeLinks_cu> InventoryStoreTreeLinks_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStoreTreeLinks_cu> InventoryStoreTreeLinks_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTrackingPeriod_cu> InventoryTrackingPeriod_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransferTransaction> InventoryTransferTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransferTransaction> InventoryTransferTransactions1 { get; set; }
    }
}
