//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem_RawMaterial_cu
    {
        public int ID { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public int RawMaterial_CU_ID { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<bool> HasDimensions { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual User_cu User_cu { get; set; }
    }
}
