//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransferTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryTransferTransaction()
        {
            this.InventoryTransactionQueues = new HashSet<InventoryTransactionQueue>();
        }
    
        public long ID { get; set; }
        public int InventoryTransactionType_P_ID { get; set; }
        public Nullable<long> InventoryHousingFrom_CU_ID { get; set; }
        public long InventoryHousingTo_CU_ID { get; set; }
        public int TransactionYear { get; set; }
        public int TransactionMonth { get; set; }
        public int TransactionDay { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string TransactionSerial { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public int UnitMeasurement_CU_ID { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> MinQuantity { get; set; }
        public Nullable<double> MaxQuantity { get; set; }
        public Nullable<double> ReorderQuantity { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual InventoryStore_cu InventoryStore_cu { get; set; }
        public virtual InventoryStore_cu InventoryStore_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransactionQueue> InventoryTransactionQueues { get; set; }
        public virtual InventoryTransactionType_p InventoryTransactionType_p { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
