//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRequestTransfer
    {
        public int ID { get; set; }
        public long InventoryHousingFrom_CU_ID { get; set; }
        public int InventoryQueueTransactionStatus_P_ID { get; set; }
        public string RequestSerial { get; set; }
        public int RequestYear { get; set; }
        public int RequestMonth { get; set; }
        public int RequestDay { get; set; }
        public double RequestedQuantity { get; set; }
        public int UnitMeasurment_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual InventoryQueueTransactionStatus_p InventoryQueueTransactionStatus_p { get; set; }
        public virtual InventoryStore_cu InventoryStore_cu { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
