//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoicePayment()
        {
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
        }
    
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<long> Patient_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int PaymentTransactionType_P_ID { get; set; }
        public int PaymentType_P_ID { get; set; }
        public double Amount { get; set; }
        public string PaymentSerial { get; set; }
        public string Description { get; set; }
        public bool IsRemainingReturned { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<int> InsertedYear { get; set; }
        public Nullable<int> InsertedMonth { get; set; }
        public Nullable<int> InsertedDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual PaymentTransactionType_p PaymentTransactionType_p { get; set; }
        public virtual PaymentType_p PaymentType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
