//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoicePayments = new HashSet<InvoicePayment>();
        }
    
        public int ID { get; set; }
        public int InvoiceType_P_ID { get; set; }
        public int InvoicePaymentType_P_ID { get; set; }
        public System.DateTime InvoiceCreationDate { get; set; }
        public long Patient_CU_ID { get; set; }
        public string InvoiceSerial { get; set; }
        public bool IsFinanciallyReviewed { get; set; }
        public Nullable<long> FinanciallyReviewedBy { get; set; }
        public Nullable<System.DateTime> FinanciallyReviewDate { get; set; }
        public bool IsFinanciallyCompleted { get; set; }
        public Nullable<long> FinanciallyCompletedBy { get; set; }
        public Nullable<System.DateTime> FinanciallyCompletedDate { get; set; }
        public bool IsMedicallyDone { get; set; }
        public bool IsSuspended { get; set; }
        public Nullable<long> SuspendedBy { get; set; }
        public Nullable<System.DateTime> SuspensionDate { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<long> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<int> InvoiceCostingStrategy_P_ID { get; set; }
        public Nullable<bool> IsPaymentEnough { get; set; }
        public Nullable<int> IsPaymentEnoughUserID { get; set; }
        public Nullable<double> PatientMaxAmount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<long> DiscountUser_CU_ID { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<int> InsertedYear { get; set; }
        public Nullable<int> InsertedMonth { get; set; }
        public Nullable<int> InsertedDay { get; set; }
    
        public virtual InvoiceCostingStrategy_p InvoiceCostingStrategy_p { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual InvoicePaymentType_p InvoicePaymentType_p { get; set; }
        public virtual InvoiceType_p InvoiceType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual User_cu User_cu1 { get; set; }
        public virtual User_cu User_cu2 { get; set; }
        public virtual User_cu User_cu3 { get; set; }
        public virtual User_cu User_cu4 { get; set; }
        public virtual User_cu User_cu5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
    }
}
