//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient_cu()
        {
            this.AppointmentTransactions = new HashSet<AppointmentTransaction>();
            this.Invoices = new HashSet<Invoice>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
        }
    
        public long Person_CU_ID { get; set; }
        public string InternalCode { get; set; }
        public string PatientBarcode { get; set; }
        public Nullable<int> InsuranceCarrier_InsuranceLevel_CU_ID { get; set; }
        public Nullable<int> PersonRelativeType_P_ID { get; set; }
        public string RelativeName { get; set; }
        public string RelativePhone { get; set; }
        public string RelativeAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransaction> AppointmentTransactions { get; set; }
        public virtual InsuranceCarrier_InsuranceLevel_cu InsuranceCarrier_InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        public virtual PersonRelativeType_p PersonRelativeType_p { get; set; }
    }
}
