//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_IdentificationCardType_cu
    {
        public int ID { get; set; }
        public long Person_CU_ID { get; set; }
        public int IdentificationCardType_CU_ID { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime IssuingDate { get; set; }
        public System.DateTime EpirationDate { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual Person_cu Person_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
