//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_p
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role_p()
        {
            this.Role_p1 = new HashSet<Role_p>();
            this.RoleRegistration_cu = new HashSet<RoleRegistration_cu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int RoleLevel { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> Application_P_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Application_p Application_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_p> Role_p1 { get; set; }
        public virtual Role_p Role_p2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRegistration_cu> RoleRegistration_cu { get; set; }
    }
}
