//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_cu()
        {
            this.AppointmentService_cu = new HashSet<AppointmentService_cu>();
            this.Service_cu1 = new HashSet<Service_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public bool IsFavorite { get; set; }
        public int ServiceCategory_CU_ID { get; set; }
        public Nullable<int> ParentService_CU_ID { get; set; }
        public string InternalCode { get; set; }
        public Nullable<double> DefaultPrice { get; set; }
        public bool SetQueue { get; set; }
        public Nullable<bool> EnforceCategorization { get; set; }
        public Nullable<bool> IsDailyCharged { get; set; }
        public bool IsAvailable { get; set; }
        public bool AllowAdmission { get; set; }
        public string Description { get; set; }
        public Nullable<int> ChartOfAccount_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentService_cu> AppointmentService_cu { get; set; }
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
        public virtual ServiceCategory_cu ServiceCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu1 { get; set; }
        public virtual Service_cu Service_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
