//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_cu()
        {
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
        }
    
        public long Person_CU_ID { get; set; }
        public Nullable<int> SupplierType_P_ID { get; set; }
        public string InternalCode { get; set; }
        public Nullable<int> Company_CU_ID { get; set; }
        public string CommercialName { get; set; }
        public string CommercialRegistrationNumber { get; set; }
        public string TaxRegistrationNumber { get; set; }
        public Nullable<double> StartingBalance { get; set; }
        public Nullable<System.DateTime> StartingBalanceDate { get; set; }
        public string Barcode { get; set; }
        public string WebSite { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        public virtual SupplierType_p SupplierType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
