//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMeasurment_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitMeasurment_cu()
        {
            this.InventoryItem_UnitMeasurment_cu = new HashSet<InventoryItem_UnitMeasurment_cu>();
            this.InventoryRequestTransfers = new HashSet<InventoryRequestTransfer>();
            this.InventoryTransferTransactions = new HashSet<InventoryTransferTransaction>();
            this.UnitMeasurment_cu1 = new HashSet<UnitMeasurment_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public Nullable<int> ParentUnitMeasurment_CU_ID { get; set; }
        public Nullable<double> EncapsulatedChildQuantity { get; set; }
        public Nullable<int> UnitMeasurment_P_ID { get; set; }
        public string InternalCode { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_UnitMeasurment_cu> InventoryItem_UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryRequestTransfer> InventoryRequestTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransferTransaction> InventoryTransferTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitMeasurment_cu> UnitMeasurment_cu1 { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu2 { get; set; }
        public virtual UnitMeasurment_p UnitMeasurment_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
