//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBusinessLogicLibrary.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_cu()
        {
            this.AppointmentDoctor_cu = new HashSet<AppointmentDoctor_cu>();
            this.AppointmentService_cu = new HashSet<AppointmentService_cu>();
            this.AppointmentTransactions = new HashSet<AppointmentTransaction>();
            this.AppointmentTransactionSendingDetails = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails1 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails2 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails3 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails4 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails5 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails6 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentTransactionSendingDetails7 = new HashSet<AppointmentTransactionSendingDetail>();
            this.AppointmentType_cu = new HashSet<AppointmentType_cu>();
            this.Bank_cu = new HashSet<Bank_cu>();
            this.BankAccount_cu = new HashSet<BankAccount_cu>();
            this.CashBox_cu = new HashSet<CashBox_cu>();
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxInOutTransactions1 = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxPrintingConfiguration_cu = new HashSet<CashBoxPrintingConfiguration_cu>();
            this.ChartOfAccount_cu = new HashSet<ChartOfAccount_cu>();
            this.ChartOfAccountBalances = new HashSet<ChartOfAccountBalance>();
            this.City_cu = new HashSet<City_cu>();
            this.Company_cu = new HashSet<Company_cu>();
            this.Country_cu = new HashSet<Country_cu>();
            this.Currency_cu = new HashSet<Currency_cu>();
            this.Department_cu = new HashSet<Department_cu>();
            this.DoctorCategory_cu = new HashSet<DoctorCategory_cu>();
            this.DoctorTaxType_cu = new HashSet<DoctorTaxType_cu>();
            this.EmployeeType_cu = new HashSet<EmployeeType_cu>();
            this.FinancialInterval_cu = new HashSet<FinancialInterval_cu>();
            this.Floor_cu = new HashSet<Floor_cu>();
            this.InsuranceCarrier_cu = new HashSet<InsuranceCarrier_cu>();
            this.InsuranceCarrier_InsuranceLevel_cu = new HashSet<InsuranceCarrier_InsuranceLevel_cu>();
            this.InsuranceLevel_cu = new HashSet<InsuranceLevel_cu>();
            this.InventoryItem_cu = new HashSet<InventoryItem_cu>();
            this.InventoryItem_PurchasingTax_cu = new HashSet<InventoryItem_PurchasingTax_cu>();
            this.InventoryItem_RawMaterial_cu = new HashSet<InventoryItem_RawMaterial_cu>();
            this.InventoryItem_SellingTax_cu = new HashSet<InventoryItem_SellingTax_cu>();
            this.InventoryItem_UnitMeasurment_cu = new HashSet<InventoryItem_UnitMeasurment_cu>();
            this.InventoryItemBrand_cu = new HashSet<InventoryItemBrand_cu>();
            this.InventoryItemCategory_cu = new HashSet<InventoryItemCategory_cu>();
            this.InventoryItemGroup_cu = new HashSet<InventoryItemGroup_cu>();
            this.InventoryItemGroup_InventoryItem_cu = new HashSet<InventoryItemGroup_InventoryItem_cu>();
            this.InventoryItemGrouping_cu = new HashSet<InventoryItemGrouping_cu>();
            this.InventoryItemGroupingItem_cu = new HashSet<InventoryItemGroupingItem_cu>();
            this.InventoryItemOffers_cu = new HashSet<InventoryItemOffers_cu>();
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
            this.InventoryItemSize_cu = new HashSet<InventoryItemSize_cu>();
            this.InventoryRequestTransfers = new HashSet<InventoryRequestTransfer>();
            this.InventoryStore_cu = new HashSet<InventoryStore_cu>();
            this.InventoryStore_Employee_cu = new HashSet<InventoryStore_Employee_cu>();
            this.InventoryStoreCategory_cu = new HashSet<InventoryStoreCategory_cu>();
            this.InventoryStoreTreeLinks_cu = new HashSet<InventoryStoreTreeLinks_cu>();
            this.InventoryTrackingPeriod_cu = new HashSet<InventoryTrackingPeriod_cu>();
            this.InventoryTransactionQueues = new HashSet<InventoryTransactionQueue>();
            this.InventoryTransferTransactions = new HashSet<InventoryTransferTransaction>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Invoices2 = new HashSet<Invoice>();
            this.Invoices3 = new HashSet<Invoice>();
            this.Invoices4 = new HashSet<Invoice>();
            this.Invoices5 = new HashSet<Invoice>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.JobTitle_cu = new HashSet<JobTitle_cu>();
            this.Location_cu = new HashSet<Location_cu>();
            this.Manager_cu = new HashSet<Manager_cu>();
            this.MedicationCategory_cu = new HashSet<MedicationCategory_cu>();
            this.Organization_cu = new HashSet<Organization_cu>();
            this.Person_ChartOfAccount_cu = new HashSet<Person_ChartOfAccount_cu>();
            this.Person_IdentificationCardType_cu = new HashSet<Person_IdentificationCardType_cu>();
            this.Person_Phone_cu = new HashSet<Person_Phone_cu>();
            this.Region_cu = new HashSet<Region_cu>();
            this.RoleRegistration_cu = new HashSet<RoleRegistration_cu>();
            this.RoleRegistration_cu1 = new HashSet<RoleRegistration_cu>();
            this.Service_cu = new HashSet<Service_cu>();
            this.ServiceCategory_cu = new HashSet<ServiceCategory_cu>();
            this.Supplier_cu = new HashSet<Supplier_cu>();
            this.Tax_cu = new HashSet<Tax_cu>();
            this.UnitMeasurment_cu = new HashSet<UnitMeasurment_cu>();
            this.User_Application_cu = new HashSet<User_Application_cu>();
            this.User_Application_cu1 = new HashSet<User_Application_cu>();
            this.User_UserGroup_cu = new HashSet<User_UserGroup_cu>();
            this.User_UserGroup_cu1 = new HashSet<User_UserGroup_cu>();
            this.UserGroup_Application_cu = new HashSet<UserGroup_Application_cu>();
            this.UserGroup_cu = new HashSet<UserGroup_cu>();
            this.WorkingShiftTitle_cu = new HashSet<WorkingShiftTitle_cu>();
        }
    
        public long Person_CU_ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> OragnizationID { get; set; }
        public string InternalCode { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentDoctor_cu> AppointmentDoctor_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentService_cu> AppointmentService_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransaction> AppointmentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTransactionSendingDetail> AppointmentTransactionSendingDetails7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentType_cu> AppointmentType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank_cu> Bank_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount_cu> BankAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBox_cu> CashBox_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxPrintingConfiguration_cu> CashBoxPrintingConfiguration_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_cu> ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccountBalance> ChartOfAccountBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City_cu> City_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_cu> Company_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country_cu> Country_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency_cu> Currency_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_cu> Department_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorCategory_cu> DoctorCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorTaxType_cu> DoctorTaxType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeType_cu> EmployeeType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialInterval_cu> FinancialInterval_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor_cu> Floor_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_cu> InsuranceCarrier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_InsuranceLevel_cu> InsuranceCarrier_InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceLevel_cu> InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_cu> InventoryItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_PurchasingTax_cu> InventoryItem_PurchasingTax_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_RawMaterial_cu> InventoryItem_RawMaterial_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_SellingTax_cu> InventoryItem_SellingTax_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_UnitMeasurment_cu> InventoryItem_UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemBrand_cu> InventoryItemBrand_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemCategory_cu> InventoryItemCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroup_cu> InventoryItemGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroup_InventoryItem_cu> InventoryItemGroup_InventoryItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGrouping_cu> InventoryItemGrouping_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroupingItem_cu> InventoryItemGroupingItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemOffers_cu> InventoryItemOffers_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemSize_cu> InventoryItemSize_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryRequestTransfer> InventoryRequestTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStore_cu> InventoryStore_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStore_Employee_cu> InventoryStore_Employee_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStoreCategory_cu> InventoryStoreCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryStoreTreeLinks_cu> InventoryStoreTreeLinks_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTrackingPeriod_cu> InventoryTrackingPeriod_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransactionQueue> InventoryTransactionQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransferTransaction> InventoryTransferTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTitle_cu> JobTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location_cu> Location_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager_cu> Manager_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationCategory_cu> MedicationCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization_cu> Organization_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_ChartOfAccount_cu> Person_ChartOfAccount_cu { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_IdentificationCardType_cu> Person_IdentificationCardType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Phone_cu> Person_Phone_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region_cu> Region_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRegistration_cu> RoleRegistration_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRegistration_cu> RoleRegistration_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_cu> ServiceCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_cu> Supplier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_cu> Tax_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitMeasurment_cu> UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Application_cu> User_Application_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Application_cu> User_Application_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserGroup_cu> User_UserGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserGroup_cu> User_UserGroup_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup_Application_cu> UserGroup_Application_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup_cu> UserGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingShiftTitle_cu> WorkingShiftTitle_cu { get; set; }
    }
}
